version: '2'
services:
    interk-app:
        image: interk
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://interk-postgresql:5432/Interk
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    interk-postgresql:
        extends:
            file: postgresql.yml
            service: interk-postgresql
